// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXAdgcs9DyPw2_J8iZgAtM_s51exKBpc8',
    appId: '1:767232163712:web:aff9fecfa20b9fe2470b65',
    messagingSenderId: '767232163712',
    projectId: 'bolt-running-app',
    authDomain: 'bolt-running-app.firebaseapp.com',
    storageBucket: 'bolt-running-app.firebasestorage.app',
    measurementId: 'G-HW860TGZHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP0JIGlZYIeC4UnCe2fgVwbSVaF_fyRF4',
    appId: '1:767232163712:android:585be52e28bf5478470b65',
    messagingSenderId: '767232163712',
    projectId: 'bolt-running-app',
    storageBucket: 'bolt-running-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbSbR_akCsc7AocYT_Ln5-Y9mNrPG25ww',
    appId: '1:767232163712:ios:1a0c167a6089cdbd470b65',
    messagingSenderId: '767232163712',
    projectId: 'bolt-running-app',
    storageBucket: 'bolt-running-app.firebasestorage.app',
    iosBundleId: 'com.example.bolt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbSbR_akCsc7AocYT_Ln5-Y9mNrPG25ww',
    appId: '1:767232163712:ios:1a0c167a6089cdbd470b65',
    messagingSenderId: '767232163712',
    projectId: 'bolt-running-app',
    storageBucket: 'bolt-running-app.firebasestorage.app',
    iosBundleId: 'com.example.bolt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXAdgcs9DyPw2_J8iZgAtM_s51exKBpc8',
    appId: '1:767232163712:web:51500b069643ce74470b65',
    messagingSenderId: '767232163712',
    projectId: 'bolt-running-app',
    authDomain: 'bolt-running-app.firebaseapp.com',
    storageBucket: 'bolt-running-app.firebasestorage.app',
    measurementId: 'G-QL7GM8K2RH',
  );
}
